### ISSUE TITLE
Incompatible with Android Studio Electric Eel 2022.1.1

### ISSUE THREAD

**Issue by 880634** [mistamek/Android-drawable-preview-plugin#17]
* Unable to display the picture, please check it out when you have time

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/24937241/213678674-9c3422e7-3393-4841-a8da-2b210b22bd53.png">

**Comment by mistamek** [comment]
Hi, is this MacOS?

**Comment by getActivity** [comment]
> Hi, is this MacOS?

yes

**Comment by 880634** [comment]
> Hi, is this MacOS?

yes

**Comment by 880634** [comment]
@mistamek Hello, did you find out what the problem is? Need my help here?

**Comment by mistamek** [comment]
@880634 Hello, I'm sorry for the delay. Can you try to install this debug build? You will need to uninstall the previous version, and drug and drop the zip file into the running Android studio. I don't have Mac, so I definitely need your help in this one :) 
[drawable_preview-1.1.6.zip](https://github.com/mistamek/Android-drawable-preview-plugin/files/10510867/drawable_preview-1.1.6.zip)

**Comment by 880634** [comment]
@mistamek Hello, the following error occurred when I started Android Studio after installing the plug-in

```text
java.lang.ArithmeticException: input is infinite or NaN java.lang.ArithmeticException: input is infinite or NaN 
    at com.google.common.math.DoubleMath.roundIntermediate(DoubleMath.java:58)
    at com.google.common.math.DoubleMath.roundToInt(DoubleMath.java:133)
    at com.android.ide.common.vectordrawable.VdPreview.getPreviewFromVectorTree(VdPreview.java:265)
    at com.android.ide.common.vectordrawable.VdPreview.getPreviewFromVectorDocument(VdPreview.java:217)
    at com.mistamek.drawablepreview.factories.XmlImageFactory.createXmlImage(XmlImageFactory.kt:41)
    at com.mistamek.drawablepreview.factories.IconPreviewFactory.getImage(IconPreviewFactory.kt:65)
    at com.mistamek.drawablepreview.factories.IconPreviewFactory.getIcon(IconPreviewFactory.kt:46)
    at com.mistamek.drawablepreview.factories.IconPreviewFactory.createIcon(IconPreviewFactory.kt:27)
    at com.mistamek.drawablepreview.DrawablePreviewIconProvider.getIcon(DrawablePreviewIconProvider.kt:9)
    at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
    at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
    at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:215)
    at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:149)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters.lambda$updateFileIconAsynchronously$5(EditorsSplitters.java:418)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:536)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:501)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1152)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:75)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:115)
    at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:58)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
    at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:58)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
    at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:75)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:501)
    at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:408)
    at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:241)
    at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:31)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:214)
    at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:206)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
    at java.base/java.lang.Thread.run(Thread.java:829) 
```

**Comment by mistamek** [comment]
Thank you! I will try to fix this on this week.

**Comment by 880634** [comment]
okay, trouble

**Comment by mistamek** [comment]
@880634 So I have changed things a little bit. Can you try this one?
[drawable_preview-1.1.6.zip](https://github.com/mistamek/Android-drawable-preview-plugin/files/10568721/drawable_preview-1.1.6.zip)

**Comment by 880634** [comment]
@mistamek No error, but the picture thumbnail is still not visible

**Comment by mistamek** [comment]
Huh, that's interesting. And default icon is showing for every type of drawables? Png, vector, shape etc?

**Comment by 880634** [comment]
Yes, all image assets display the default icon.

**Comment by md0092651** [comment]
Any update on the release of the fix?

**Comment by mistamek** [comment]
Well, I don't know what can I do with this one.

**Comment by 880634** [comment]
@mistamek Hello, if the problem is fixed, you can send it to me for testing

**Comment by mistamek** [comment]
Nope, problem not fixed, and I don''t know how to fix it right now.

**Comment by md0092651** [comment]
The vector drawable thumbnails plugin seems to work but that not exactly what we wanted 😞

**Comment by wenwenwen888** [comment]
Hi , I have the same problem with Android Studio 2021.2.1 Patch 2 .

**Comment by KirillBorodin** [comment]
Same on my side.

```
Android Studio Electric Eel | 2022.1.1 Patch 1
Build #AI-221.6008.13.2211.9514443, built on January 21, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.2.1
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    external.system.auto.import.disabled=true
    ide.text.editor.with.preview.show.floating.toolbar=false
    ide.instant.shutdown=false

Non-Bundled Plugins:
    com.intellij.plugins.macoskeymap (221.6008.13)
    org.intellij.plugins.markdown (221.5787.39)
    com.herbert.george.flutter-snippets (2.1.1-stable-1)
    com.bloc.intellij_generator_plugin (3.4.0)
    mobi.hsz.idea.gitignore (4.4.0)
    Dart (221.6103)
    com.localizely.flutter-intl (1.18.1-2020.3)
    com.ixigua.flutter_asset_iteral (1.7.7)
    com.mistamek.drawablepreview.drawable-preview (1.1.6)
    io.flutter (72.1.2)
```

**Comment by wxlibowen** [comment]
> @880634 So I have changed things a little bit. Can you try this one? [drawable_preview-1.1.6.zip](https://github.com/mistamek/Android-drawable-preview-plugin/files/10568721/drawable_preview-1.1.6.zip)
The following error occurred when I used this jar package
null kotlin.Unit

**Comment by KirillBorodin** [comment]
Okay, I've tried [drawable_preview-1.1.6.zip](https://github.com/mistamek/Android-drawable-preview-plugin/files/10568721/drawable_preview-1.1.6.zip), but unfortunately nothing changed.
<img width="334" alt="image" src="https://user-images.githubusercontent.com/29107059/226088096-4944e9e7-05de-48b7-a2bb-59a805ab30c4.png">
<img width="531" alt="image" src="https://user-images.githubusercontent.com/29107059/226088105-f4b2b05c-26be-47ca-9c89-673cbb389cab.png">
 

> > @880634 So I have changed things a little bit. Can you try this one? [drawable_preview-1.1.6.zip](https://github.com/mistamek/Android-drawable-preview-plugin/files/10568721/drawable_preview-1.1.6.zip)
> > The following error occurred when I used this jar package
> > null kotlin.Unit

**Comment by guoshilun** [comment]
The Mac M2 system is also incompatible

**Comment by guoshilun** [comment]
I hope it can be revised earlier, thank you

**Comment by WinWang** [comment]
Is there any result?

**Comment by AndrewTseZhou** [comment]
Is there a fixed version? AS 202.2.1 also has problems.

**Comment by Samdogcom** [comment]
This plugin works fine but xml file can't preview.
Image Icon Viewer

**Comment by mtrakal** [comment]
You can check https://github.com/mistamek/Android-drawable-preview-plugin/issues/18#issuecomment-1641623990 if it will be helpfull for you too, but with no guarantee :). Check the source code too and you can fix it by yourself in Intellij Idea Community edition.
