### ISSUE TITLE
Preview does not work on Android Studio Flamingo | 2022.2.1 Patch 1

### ISSUE THREAD

**Issue by Hayk985** [mistamek/Android-drawable-preview-plugin#18]
<img width="351" alt="Screenshot 2023-05-25 at 11 20 19" src="https://github.com/mistamek/Android-drawable-preview-plugin/assets/30463912/faff942b-577b-4dcc-a23b-a3024f0e8f25">

**Comment by mtrakal** [comment]
Android Studio Hedgehog | 2023.1.1 Canary 12
Build #AI-231.9161.38.2311.10457801, built on July 7, 2023
Runtime version: 17.0.7+0-b2043.56-10353782 amd64

Hadgehog not working too

**Comment by 932707629** [comment]
Android Studio Flamingo | 2022.2.1 Patch 2
Build #AI-222.4459.24.2221.10121639, built on May 12, 2023
Runtime version: 17.0.6+0-17.0.6b802.4-9586694 x86_64

me too

**Comment by mtrakal** [comment]
Pull request with changes: https://github.com/mistamek/Android-drawable-preview-plugin/pull/19

If someone want to download compiled version, it's here: http://android.mtrakal.cz/instrumented-drawable-preview-1.1.7.jar

Without no guarantee of work, but for me it's working in Hedgehog.

**Comment by spianmo** [comment]
> Pull request with changes: https://github.com/mistamek/Android-drawable-preview-plugin/pull/19
> 
> 
> 
> If someone want to download compiled version, it's here: http://android.mtrakal.cz/instrumented-drawable-preview-1.1.7.jar
> 
> 
> 
> Without no guarantee of work, but for me it's working in Hedgehog.

The XML format seems to be unable to display properly

**Comment by mtrakal** [comment]
@spianmo any closer info? Android studio version, what do you mean by _unable to display properly_? Like, show drawable but broken, not show at all,  show only some of drawable? From developer I expect better issue description :D

Standard developer response: work for me :D

<img width="289" alt="image" src="https://github.com/mistamek/Android-drawable-preview-plugin/assets/1458891/4fd7add2-78e1-48b2-8607-fc043b774eb2">

**Comment by spianmo** [comment]
> @spianmo any closer info? Android studio version, what do you mean by _unable to display properly_? Like, show drawable but broken, not show at all, show only some of drawable? From developer I expect better issue description :D
> 
> Standard developer response: work for me :D
> 
> <img alt="image" width="289" src="https://user-images.githubusercontent.com/1458891/254563307-4fd7add2-78e1-48b2-8607-fc043b774eb2.png">

**OS：** macOS Sonoma  14.0 Beta(23A5286i)
**Android Studio：** Android Studio Giraffe | 2022.3.1 RC 1 Build #AI-223.8836.35.2231.10320515, built on June 14, 2023
**Jetbrains IDE runtime (jbr)：** Java17.0.6 JetBrains Runtime  Bundled
![image](https://github.com/mistamek/Android-drawable-preview-plugin/assets/18194268/acf02812-267d-4a63-bfd4-95ef9a0029cc)

**Comment by spianmo** [comment]
The png display is normal, but the xml display is not normal
![image](https://github.com/mistamek/Android-drawable-preview-plugin/assets/18194268/cd6b0a0c-85e5-4d63-b19b-a6aa87e724d3)

**Comment by spianmo** [comment]
```
2023-07-19 20:13:15,226 [  39110]   INFO - #o.j.p.g.GradleManager - Instructing gradle to use java from /Users/finger/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-2/223.8836.35.2231.10320515/Android Studio.app/Contents/jbr/Contents/Home
2023-07-19 20:13:15,414 [  39298] SEVERE - #o.j.c.AsyncPromise - 'com.android.tools.configurations.Configuration com.android.tools.idea.configurations.ConfigurationManager.getConfiguration(com.intellij.openapi.vfs.VirtualFile)'
java.lang.NoSuchMethodError: 'com.android.tools.configurations.Configuration com.android.tools.idea.configurations.ConfigurationManager.getConfiguration(com.intellij.openapi.vfs.VirtualFile)'
	at com.mistamek.drawablepreview.factories.XmlImageFactory.getResourceResolver(XmlImageFactory.kt:113)
	at com.mistamek.drawablepreview.factories.XmlImageFactory.parseDocument(XmlImageFactory.kt:57)
	at com.mistamek.drawablepreview.factories.XmlImageFactory.createXmlImage(XmlImageFactory.kt:28)
	at com.mistamek.drawablepreview.factories.IconPreviewFactory.getImage(IconPreviewFactory.kt:54)
	at com.mistamek.drawablepreview.factories.IconPreviewFactory.getIcon(IconPreviewFactory.kt:35)
	at com.mistamek.drawablepreview.factories.IconPreviewFactory.createIcon(IconPreviewFactory.kt:22)
	at com.mistamek.drawablepreview.DrawablePreviewIconProvider.getIcon(DrawablePreviewIconProvider.kt:9)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:21)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:37)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:227)
	at com.intellij.util.IconUtil.computeFileIcon(IconUtil.java:156)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.updateFileIconAsynchronously$lambda$10(EditorsSplitters.kt:414)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:746)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:778)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:573)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1111)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:128)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:109)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:68)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:68)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:106)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:71)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:444)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:243)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:29)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.executeFirstTaskAndHelpQueue(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:208)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
2023-07-19 20:13:15,415 [  39299] SEVERE - #o.j.c.AsyncPromise - Android Studio Giraffe | 2022.3.1 RC 1  Build #AI-223.8836.35.2231.10320515
2023-07-19 20:13:15,415 [  39299] SEVERE - #o.j.c.AsyncPromise - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-07-19 20:13:15,415 [  39299] SEVERE - #o.j.c.AsyncPromise - OS: Mac OS X
2023-07-19 20:13:15,416 [  39300] SEVERE - #o.j.c.AsyncPromise - Plugin to blame: Android Drawable Preview version: 1.1.7
```

**Comment by spianmo** [comment]
@mtrakal It seems that the error occurs when creating the XmlImage, in com.mistamek.drawablepreview.factories.XmlImageFactory.getResourceResolver, is it because of the java runtime of the ide?

**Comment by spianmo** [comment]
> It seems that the error occurs when creating the XmlImage, in com.mistamek.drawablepreview.factories.XmlImageFactory.getResourceResolver, is it because of the java runtime of the ide?

@mtrakal

**Comment by mtrakal** [comment]
@spianmo 

Looks, that works for some icon(s): 
<img width="435" alt="image" src="https://github.com/mistamek/Android-drawable-preview-plugin/assets/1458891/5391405a-da04-49fc-91da-89269e4989eb">

But as I checked here there will be some other issue with macOS: https://github.com/mistamek/Android-drawable-preview-plugin/issues/17 not primarily related to new Android Studio as this issue. I'm using Hedgehog  as mentioned in linked PR + Windows. I'm not sure that I'm able to fix it for Mac.

 But you can try fix it same as me:
- install IntelliJ Idea Community 
- clone repo with my PR
- edit path to Android Studio: https://github.com/mistamek/Android-drawable-preview-plugin/pull/19/files#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06R58
- Run plugin from IntellJ Idea and it will start sanboxed Android Studio (clean AS just with this plugin installed).

Can you provide some of not working XML icon files? I'll try them on Windows, if it works.

**Comment by spianmo** [comment]
@mtrakal Grateful!

**Comment by mxdlsm** [comment]
> png显示正常，xml显示不正常 ![图像](https://user-images.githubusercontent.com/18194268/254568215-cd6b0a0c-85e5-4d63-b19b-a6aa87e724d3.png)

Hello, I also encountered this problem, may I ask if it has been solved?

**Comment by WinWang** [comment]
> > png显示正常，xml显示不正常 ![图像](https://user-images.githubusercontent.com/18194268/254568215-cd6b0a0c-85e5-4d63-b19b-a6aa87e724d3.png)
> 
> Hello, I also encountered this problem, may I ask if it has been solved?

me too

**Comment by spianmo** [comment]
@WinWang Android Studio Hedgehog | 2023.1.1 Canary 12 works well

**Comment by WinWang** [comment]
> @WinWang Android Studio Hedgehog | 2023.1.1 Canary 12 works well

My Version is Android Studio Giraffe | 2022.3.1

**Comment by Slion** [comment]
[That](https://github.com/mistamek/Android-drawable-preview-plugin/issues/18#issuecomment-1641623990) fixed it for me on Android Studio Hedgehog | 2023.1.1 Patch 1.
Hopefuly the owner will merge and update that at some point.

**Comment by Merkost** [comment]
#21 Just added support for Android Studio Jellyfish

**Comment by hust-twj** [comment]
Support for : Android Studio Meerkat | 2024.3.1 
- Plugin:  https://plugins.jetbrains.com/plugin/27146-android-drawable-preview-pro
- Source code: https://github.com/hust-twj/Android-drawable-preview-pro-plugin
