### ISSUE TITLE
icon not visible .......java.lang.IndexOutOfBoundsException: Index: 0, Size: 0

### ISSUE THREAD

**Issue by birjubhatt** [mistamek/Android-drawable-preview-plugin#2]
Index: 0, Size: 0
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.androhi.androiddrawableviewer.model.DrawableModel.getLowDensityFilePath(DrawableModel.kt:45)
	at com.androhi.androiddrawableviewer.form.DrawableViewer.createPanels(DrawableViewer.kt:114)
	at com.androhi.androiddrawableviewer.form.DrawableViewer.createContentPanel(DrawableViewer.kt:47)
	at com.androhi.androiddrawableviewer.form.DrawableViewer.<init>(DrawableViewer.kt:33)
	at com.androhi.androiddrawableviewer.form.AndroidDrawableViewerToolWindowFactory.createToolWindowContent

**Comment by mistamek** [comment]
Hi, birjubhatt, can you provide resource that crashing?

**Comment by mistamek** [comment]
And if you look at package name, you can see that it from this plugin https://github.com/androhi/AndroidDrawableViewer
