### ISSUE TITLE
as 3.3 Canary 8 not work

### ISSUE THREAD

**Issue by mapengshen** [mistamek/Android-drawable-preview-plugin#6]
java.lang.NoSuchMethodError: com.android.tools.idea.rendering.GutterIconFactory.createIcon(Ljava/lang/String;Lcom/android/ide/common/resources/ResourceResolver;II)Ljavax/swing/Icon;
	at IconPreviewFactory$Companion.createIconInner(IconPreviewFactory.kt:57)
	at IconPreviewFactory$Companion.createIcon(IconPreviewFactory.kt:43)
	at DrawablePreviewIconProvider.getIcon(DrawablePreviewIconProvider.kt:7)
	at com.intellij.util.PsiIconUtil.getProvidersIcon(PsiIconUtil.java:42)
	at com.intellij.ide.FileIconPatcherImpl.getIcon(FileIconPatcherImpl.java:40)
	at com.intellij.util.IconUtil.getProvidersIcon(IconUtil.java:184)
	at com.intellij.util.IconUtil.lambda$static$0(IconUtil.java:139)
	at com.intellij.ui.DeferredIconImpl.evaluate(DeferredIconImpl.java:282)
	at com.intellij.ui.DeferredIconImpl.lambda$null$0(DeferredIconImpl.java:167)
	at com.intellij.ui.IconDeferrerImpl.evaluateDeferred(IconDeferrerImpl.java:114)
	at com.intellij.ui.DeferredIconImpl.lambda$null$1(DeferredIconImpl.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1164)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:123)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:112)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:91)
	at com.intellij.ui.DeferredIconImpl.lambda$paintIcon$4(DeferredIconImpl.java:166)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:226)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$100(BoundedTaskExecutor.java:26)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2$1.run(BoundedTaskExecutor.java:199)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:229)
	at com.intellij.util.concurrency.BoundedTaskExecutor$2.run(BoundedTaskExecutor.java:193)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by mistamek** [comment]
Hi, thank you for the information. I fixed the error, and will upload a new version next week.
